name: Build and Deploy to Firebase App Distribution

on:
  push:
    branches:
      - main # Запускается при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Устанавливаем JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # Декодируем keystore из Base64
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 -d > myapp.keystore

      # Создаем файл учетных данных Firebase
      - name: Create Firebase Service Account File
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > service-account-key.json

      # Даем права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Собираем подписанный APK
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      # Загружаем APK в Firebase App Distribution
      - name: Upload to Firebase App Distribution
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew appDistributionUploadRelease